// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgplhtxxbihdwktjessj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxncGxodHh4YmloZHdrdGplc3NqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxODExNTQsImV4cCI6MjA2MDc1NzE1NH0.IsNG5FCKgOzDA1xTHxlr-uZfBUdTtlbhkDmcsRGC-4g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);